### ecrire un article
POST http://localhost:2900/article/ecrire

Content-Type: application/json
{
    "title": "Installer MongoDB",
    "subtitle": "Doc de ref",
    "description": "http....",
    "chapterId": 5
}